BEGIN;

CREATE TABLE IF NOT EXISTS currencies (
  id SERIAL PRIMARY KEY,
  code CHARACTER VARYING(30) NOT NULL
);

INSERT INTO currencies (id, code) VALUES 
(1, 'USD'),
(2, 'COP'),
(3, 'MXN');

COMMIT;